export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",

  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_DELETE: "customers.delete",

  VEHICLES_VIEW: "vehicles.view",
  VEHICLES_CREATE: "vehicles.create",
  VEHICLES_UPDATE: "vehicles.update",
  VEHICLES_DELETE: "vehicles.delete",

  APPOINTMENTS_VIEW: "appointments.view",
  APPOINTMENTS_CREATE: "appointments.create",
  APPOINTMENTS_UPDATE: "appointments.update",
  APPOINTMENTS_DELETE: "appointments.delete",

  SERVICES_VIEW: "services.view",
  SERVICES_CREATE: "services.create",
  SERVICES_UPDATE: "services.update",
  SERVICES_DELETE: "services.delete",
  SERVICES_MANAGE_PARTS: "services.manage_parts",

  INVOICES_VIEW: "invoices.view",
  INVOICES_CREATE: "invoices.create",
  INVOICES_UPDATE: "invoices.update",
  INVOICES_DELETE: "invoices.delete",
  INVOICES_MARK_PAID: "invoices.mark_paid",

  INVENTORY_VIEW: "inventory.view",
  INVENTORY_CREATE: "inventory.create",
  INVENTORY_UPDATE: "inventory.update",
  INVENTORY_DELETE: "inventory.delete",
  INVENTORY_MANAGE_STOCK: "inventory.manage_stock",

  PURCHASES_VIEW: "purchases.view",
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_UPDATE: "purchases.update",
  PURCHASES_DELETE: "purchases.delete",
  PURCHASES_RECEIVE: "purchases.receive",

  MARKETPLACE_VIEW: "marketplace.view",
  MARKETPLACE_MANAGE: "marketplace.manage",

  ANALYTICS_VIEW: "analytics.view",

  AUDIT_VIEW: "audit.view",

  STAFF_VIEW: "staff.view",
  STAFF_CREATE: "staff.create",
  STAFF_UPDATE: "staff.update",
  STAFF_DELETE: "staff.delete",
  STAFF_MANAGE_ROLES: "staff.manage_roles",

  SETTINGS_VIEW: "settings.view",
  SETTINGS_UPDATE: "settings.update",

  BILLING_VIEW: "billing.view",
  BILLING_MANAGE: "billing.manage",
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  OWNER: ALL_PERMISSIONS,

  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.CUSTOMERS_DELETE,

    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.VEHICLES_CREATE,
    PERMISSIONS.VEHICLES_UPDATE,
    PERMISSIONS.VEHICLES_DELETE,

    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_DELETE,

    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.SERVICES_CREATE,
    PERMISSIONS.SERVICES_UPDATE,
    PERMISSIONS.SERVICES_DELETE,
    PERMISSIONS.SERVICES_MANAGE_PARTS,

    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_UPDATE,
    PERMISSIONS.INVOICES_DELETE,
    PERMISSIONS.INVOICES_MARK_PAID,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.INVENTORY_MANAGE_STOCK,

    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_UPDATE,
    PERMISSIONS.PURCHASES_DELETE,
    PERMISSIONS.PURCHASES_RECEIVE,

    PERMISSIONS.MARKETPLACE_VIEW,
    PERMISSIONS.MARKETPLACE_MANAGE,

    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,

    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_UPDATE,

    PERMISSIONS.SETTINGS_VIEW,
  ],

  RECEPTIONIST: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,

    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.VEHICLES_CREATE,
    PERMISSIONS.VEHICLES_UPDATE,

    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_DELETE,

    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.SERVICES_CREATE,
    PERMISSIONS.SERVICES_UPDATE,

    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_UPDATE,

    PERMISSIONS.MARKETPLACE_VIEW,
  ],

  MECHANIC: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMERS_VIEW,

    PERMISSIONS.VEHICLES_VIEW,

    PERMISSIONS.APPOINTMENTS_VIEW,

    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.SERVICES_UPDATE,
    PERMISSIONS.SERVICES_MANAGE_PARTS,

    PERMISSIONS.INVENTORY_VIEW,
  ],

  WAREHOUSE: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.INVENTORY_MANAGE_STOCK,

    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_UPDATE,
    PERMISSIONS.PURCHASES_DELETE,
    PERMISSIONS.PURCHASES_RECEIVE,
  ],

  ACCOUNTANT: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.SERVICES_VIEW,

    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_UPDATE,
    PERMISSIONS.INVOICES_MARK_PAID,

    PERMISSIONS.PURCHASES_VIEW,

    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
};

export function getRolePermissions(role) {
  if (!role) {
    return [];
  }

  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role, permission) {
  if (!role || !permission) {
    return false;
  }

  const permissions = getRolePermissions(role);

  return permissions.includes(permission);
}

export function hasAnyPermission(role, permissions = []) {
  if (!Array.isArray(permissions) || permissions.length === 0) {
    return true;
  }

  return permissions.some((permission) => hasPermission(role, permission));
}

export function hasAllPermissions(role, permissions = []) {
  if (!Array.isArray(permissions) || permissions.length === 0) {
    return true;
  }

  return permissions.every((permission) => hasPermission(role, permission));
}
