"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireBusinessActionPermission } from "@/lib/business-context";
import { db } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";
import { createAuditLog } from "@/services/audit-log-service";

const text=(fd,key)=>String(fd.get(key)||"").trim();
export async function createExpenseAction(formData){ const c=await requireBusinessActionPermission(PERMISSIONS.FINANCE_MANAGE); const amount=Number(text(formData,"amount")); const date=new Date(`${text(formData,"expenseDate")}T12:00:00`); if(!text(formData,"description")||!Number.isFinite(amount)||amount<=0||Number.isNaN(date.getTime())) throw new Error("Plotëso përshkrimin, shumën dhe datën."); let categoryId=text(formData,"categoryId")||null; const newCategory=text(formData,"newCategory"); if(newCategory){ const cat=await db.expenseCategory.upsert({where:{businessId_name:{businessId:c.businessId,name:newCategory}},update:{isActive:true},create:{businessId:c.businessId,name:newCategory}}); categoryId=cat.id; } const expense=await db.businessExpense.create({data:{businessId:c.businessId,recordedById:c.userId,categoryId,description:text(formData,"description"),supplier:text(formData,"supplier")||null,documentNumber:text(formData,"documentNumber")||null,amount,paymentMethod:text(formData,"paymentMethod")||"CASH",expenseDate:date,notes:text(formData,"notes")||null}}); await createAuditLog({businessId:c.businessId,userId:c.userId,action:"CREATE",entityType:"BusinessExpense",entityId:expense.id,title:"U regjistrua shpenzim",description:`${expense.description}: ${amount} ALL`,newValues:{amount,expenseDate:date}}); revalidatePath("/dashboard/finance"); revalidatePath("/dashboard/finance/expenses"); redirect("/dashboard/finance/expenses?created=1"); }
export async function createInventoryCountAction(formData){ const c=await requireBusinessActionPermission(PERMISSIONS.INVENTORY_COUNTS_MANAGE); const parts=await db.part.findMany({where:{businessId:c.businessId},orderBy:{name:"asc"}}); if(!parts.length) throw new Error("Nuk ka pjesë në inventar."); const count=await db.inventoryCount.create({data:{businessId:c.businessId,createdById:c.userId,name:text(formData,"name")||`Inventarizim ${new Date().toLocaleDateString("sq-AL")}`,periodType:text(formData,"periodType")||"MONTHLY",countDate:new Date(`${text(formData,"countDate")}T12:00:00`),notes:text(formData,"notes")||null,items:{create:parts.map(p=>({partId:p.id,partName:p.name,partCode:p.code,expectedQuantity:p.stock,unitCost:p.buyPrice,expectedValue:p.stock*p.buyPrice}))}}}); await createAuditLog({businessId:c.businessId,userId:c.userId,action:"CREATE",entityType:"InventoryCount",entityId:count.id,title:"U krijua inventarizim",description:count.name}); redirect(`/dashboard/finance/inventory-counts/${count.id}`); }
export async function saveInventoryCountAction(formData){ const c=await requireBusinessActionPermission(PERMISSIONS.INVENTORY_COUNTS_MANAGE); const id=text(formData,"inventoryCountId"); const count=await db.inventoryCount.findFirst({where:{id,businessId:c.businessId},include:{items:true}}); if(!count||count.status!=="DRAFT") throw new Error("Inventarizimi nuk mund të ndryshohet."); await db.$transaction(count.items.map(item=>{ const actual=Math.max(0,Math.trunc(Number(formData.get(`actual_${item.id}`)??item.expectedQuantity))); const difference=actual-item.expectedQuantity; return db.inventoryCountItem.update({where:{id:item.id},data:{actualQuantity:actual,difference,actualValue:actual*item.unitCost,differenceValue:difference*item.unitCost,note:text(formData,`note_${item.id}`)||null}})})); revalidatePath(`/dashboard/finance/inventory-counts/${id}`); }
export async function submitInventoryCountAction(formData){ const c=await requireBusinessActionPermission(PERMISSIONS.INVENTORY_COUNTS_MANAGE); const id=text(formData,"inventoryCountId"); const count=await db.inventoryCount.findFirst({where:{id,businessId:c.businessId},include:{items:true}}); if(!count||count.status!=="DRAFT"||count.items.some(i=>i.actualQuantity===null)) throw new Error("Plotëso sasitë reale para dërgimit për shqyrtim."); await db.inventoryCount.update({where:{id},data:{status:"IN_REVIEW",submittedAt:new Date()}}); revalidatePath(`/dashboard/finance/inventory-counts/${id}`); }
export async function approveInventoryCountAction(formData){ const c=await requireBusinessActionPermission(PERMISSIONS.INVENTORY_COUNTS_APPROVE); const id=text(formData,"inventoryCountId"); const count=await db.inventoryCount.findFirst({where:{id,businessId:c.businessId,status:"IN_REVIEW"}}); if(!count) throw new Error("Inventarizimi nuk është në shqyrtim."); await db.inventoryCount.update({where:{id},data:{status:"APPROVED",approvedAt:new Date(),approvedById:c.userId}}); revalidatePath(`/dashboard/finance/inventory-counts/${id}`); }
export async function postInventoryCountAction(formData){ const c=await requireBusinessActionPermission(PERMISSIONS.INVENTORY_COUNTS_APPROVE); const id=text(formData,"inventoryCountId"); const count=await db.inventoryCount.findFirst({where:{id,businessId:c.businessId,status:"APPROVED"},include:{items:true}}); if(!count) throw new Error("Inventarizimi nuk është aprovuar."); await db.$transaction(async tx=>{ for(const item of count.items){ if(item.actualQuantity===null||item.actualQuantity===item.expectedQuantity) continue; const part=await tx.part.findFirst({where:{id:item.partId,businessId:c.businessId}}); if(!part) continue; await tx.part.update({where:{id:part.id},data:{stock:item.actualQuantity}}); await tx.inventoryMovement.create({data:{businessId:c.businessId,partId:part.id,userId:c.userId,type:item.difference>0?"ADJUSTMENT_IN":"ADJUSTMENT_OUT",quantity:Math.abs(item.difference||0),stockBefore:part.stock,stockAfter:item.actualQuantity,note:`Korrigjim nga ${count.name}`}}); } await tx.inventoryCount.update({where:{id},data:{status:"POSTED",postedAt:new Date()}}); }); await createAuditLog({businessId:c.businessId,userId:c.userId,action:"STATUS_CHANGE",entityType:"InventoryCount",entityId:id,title:"Inventarizimi u postua",description:count.name}); revalidatePath("/dashboard/inventory"); revalidatePath("/dashboard/inventory/movements"); revalidatePath(`/dashboard/finance/inventory-counts/${id}`); }
